// <auto-generated />
using System;
using Chet.QuartzNet.EFCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chet.QuartzNet.EFCore.PostgreSQL.Migrations
{
    [DbContext(typeof(QuartzDbContext))]
    partial class QuartzDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chet.QuartzNet.Models.Entities.QuartzJobInfo", b =>
                {
                    b.Property<string>("JobName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("作业名称");

                    b.Property<string>("JobGroup")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("DEFAULT")
                        .HasComment("作业分组");

                    b.Property<string>("ApiBody")
                        .HasColumnType("text")
                        .HasComment("API请求体(JSON格式)");

                    b.Property<string>("ApiHeaders")
                        .HasColumnType("text")
                        .HasComment("API请求头(JSON格式)");

                    b.Property<string>("ApiMethod")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("GET")
                        .HasComment("API请求方法");

                    b.Property<int>("ApiTimeout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30000)
                        .HasComment("API超时时间(毫秒)");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("创建人");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Cron表达式");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("作业描述");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("结束时间");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("是否启用");

                    b.Property<string>("JobClassOrApi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("作业类名或API URL");

                    b.Property<string>("JobData")
                        .HasColumnType("text")
                        .HasComment("作业数据(JSON格式)");

                    b.Property<int>("JobType")
                        .HasColumnType("integer")
                        .HasComment("作业类型");

                    b.Property<DateTime?>("NextRunTime")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("下次执行时间");

                    b.Property<DateTime?>("PreviousRunTime")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("上次执行时间");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("备注");

                    b.Property<bool>("SkipSslValidation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("是否跳过SSL验证");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("开始时间");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("作业状态");

                    b.Property<string>("TriggerGroup")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("DEFAULT")
                        .HasComment("触发器分组");

                    b.Property<string>("TriggerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("触发器名称");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("更新人");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("更新时间");

                    b.HasKey("JobName", "JobGroup");

                    b.HasIndex("CreateTime")
                        .HasDatabaseName("idx_job_create_time");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("idx_job_enabled");

                    b.HasIndex("NextRunTime")
                        .HasDatabaseName("idx_job_next_run_time");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_job_status");

                    b.ToTable("quartz_jobs", (string)null);
                });

            modelBuilder.Entity("Chet.QuartzNet.Models.Entities.QuartzJobLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("日志ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<long?>("Duration")
                        .HasColumnType("bigint")
                        .HasComment("执行耗时(毫秒)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("结束时间");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasComment("错误信息");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("text")
                        .HasComment("错误堆栈");

                    b.Property<string>("Exception")
                        .HasColumnType("text")
                        .HasComment("异常信息");

                    b.Property<string>("JobData")
                        .HasColumnType("text")
                        .HasComment("执行参数");

                    b.Property<string>("JobGroup")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("DEFAULT")
                        .HasComment("作业分组");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("作业名称");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasComment("执行结果消息");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasComment("执行结果");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("开始时间");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("日志状态");

                    b.Property<string>("TriggerGroup")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("DEFAULT")
                        .HasComment("触发器分组");

                    b.Property<string>("TriggerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("触发器名称");

                    b.HasKey("LogId");

                    b.HasIndex("CreateTime")
                        .HasDatabaseName("idx_log_create_time");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("idx_log_start_time");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_log_status");

                    b.HasIndex("JobName", "JobGroup")
                        .HasDatabaseName("idx_log_job");

                    b.ToTable("quartz_job_logs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
